### ISSUE TITLE
OAuth 2 - Implicit Flow, Access Token not loaded 

### ISSUE THREAD

**Issue by janzen01** [AntonShuvaev/jet-client-support#34]
**Describe the bug**
I configured OAuth 2 Implicit Grant flow via Microsoft Entra. The Access Token call was successful, and Entra issued an Access Token, but this token was not loaded to the plugin config.

![image](https://github.com/AntonShuvaev/jet-client-support/assets/45731360/42020e30-ab5a-4345-ab38-12068b298a9b)
![image](https://github.com/AntonShuvaev/jet-client-support/assets/45731360/6bf91281-aa9b-41d1-8cc6-1f4c1b2471ec)

**Steps to reproduce**

1. Set OAuth 2 as the Auth type
2. Choose Implicit as Grant Type
3. On Microsoft Entra (formerly Azure Active Directory), register an application to be able to obtain a Client ID and configure Redirect URIs --> Web
4. In plugin OAuth 2 Options set:
   - Auth URL: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
   - Check: Authorize using a browser
   - Client ID: UUID obtained from App registration
5. Hit the "GET NEW ACCESS TOKEN" button

**Expected behavior**
After hitting the button, Call Auth Service and automatically import obtained token to the plugin configuration.

**Environment information:**
- OS: Windows 11 23H2 (OS Build 22631.2262)
- IDE version: IntelliJ IDEA 2023.2.1 (Ultimate Edition), Build #IU-232.9559.62, built on August 23, 2023
- plugin version: 2023.1.14-232

**Comment by AntonShuvaev** [comment]
Thanks for reporting the issue. I will look into it.

**Comment by AntonShuvaev** [comment]
The behavior you're observing is actually expected due to the nature of OAuth 2.0's Implicit Grant flow.
In the "Implicit" grant flow, the access token is sent as a URL fragment (#access_token=token). According to HTTP specifications, the fragment part of the URL is never sent to the server; it's designed to be processed client-side.

This means that when you authorize using an external browser, the browser itself will not forward this fragment back to the plugin, thus it can't be automatically imported.

There are two ways to work around this:
- Disable the Authorize using browser option to use the built-in browser
- Manually copy-paste the access token from the URL

**Comment by janzen01** [comment]
Thank you for your investigation. I will look into it. :)
