### ISSUE TITLE
Does not show JetClient options

### ISSUE THREAD

**Issue by gandalfblanco** [AntonShuvaev/jet-client-support#93]
**Describe the bug**.

When selecting from the right side panel “JetClient Tools” it shows nothing, no options.  There is only a message that says “Nothing to Show”.

**Steps to reproduce the problem.
 **Expected behavior** 
The ones that allow me to work with the plugins should appear, such as:
- Import
- Globals or Draft folders.

In short, it should show me the main working screen:
https://plugins.jetbrains.com/plugin/21173-jetclient--the-ultimate-rest-client
But it does not show anything.

**Environment information
- OPERATING SYSTEM: Windows 11 Home, Version 23H2 (Build 22631.3880)

- IDE Version:
IntelliJ IDEA 2024.1.4 (Ultimate Edition).
Build #IU-241.18034.62, built on June 20, 2024
Runtime version: 17.0.11+1-b1207.24 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  com.berzanmikaili.intellij.monokai_pro (2.0.2c)
  com.jetbrains.CyanTheme (1.3)
  monokai-pro (1.10)
  com.codigrate.everest.theme (1.0.19)
  com.intellij.laf.macos 

![Ejemplo](https://github.com/user-attachments/assets/c0293621-505a-4bac-8209-3e60ec2d11bf)

**Comment by AntonShuvaev** [comment]
Hi, the behavior you're seeing is expected due to recent changes. The main JetClient tool window now defaults to the left side, but you can move it back to the right by dragging the tab. The "JetClient Tools" tool window shows Preview, Documentation, and Snippet generation only when a request is open. The "JetClient Console" displays logs when requests are executed.
